### ISSUE TITLE
Cannot create account

### ISSUE THREAD

**Issue by greenreader9** [mahtab2003/MOFHY-Lite#1]
No matter what I do, I cannot create the Admin account. After the installation is complete, it just redirects back to the "Start Installation" page. If I rename the installation directory, and attempt to login, I just get "The account does not exists" message. MOFHY is installed in the "/clients" directory. When asked for the URL, "/clients/" is the only one that allows the "Signup" link to work. After each failed creation attempt, I created a new database. Is there something wrong with installation?

**Comment by mahtab2003** [comment]
Reinstall the mofy lite

**Comment by mahtab2003** [comment]
You need to login at ```your domain/clients/admin/```

**Comment by greenreader9** [comment]
"You need to login at your domain/clients/admin/" Duh. Somehow I forgot that. Thanks!
