### ISSUE TITLE
Domain not shown

### ISSUE THREAD

**Issue by jaikt** [mahtab2003/MOFHY-Lite#10]
Hi, when a user creates an account with a subdomain like (sub.blogystar.com) or with a custom domain like (example.com). But wherever the domain name is shown like in `myaccounts.php` the main domain is displayed i.e (xxxxxx.blogystar.com). Is there any fix? I have already 1000 clients. Reinstalling is not my choice. I understand that previous hosting accounts data may not be changed. But for new hosting accounts, there would've been a solution.

**Comment by jaikt** [comment]
Also is there anyway to upgrade mofhy without loosing clients and hosting account data?

**Comment by greenreader9** [comment]
The main domain is different from the domain(s) the user adds. The main domain is displayed on myaccounts.php, and the clients domains can be viewed on viewaccount.php at the bottom of the page.

If you want to display the clients domain on myaccounts.php, you are going to have to do some coding. 

or your second question, yes, you can. Just don't delete the database.
