### ISSUE TITLE
!IMPORTANT! SQL Injection vulneraries 

### ISSUE THREAD

**Issue by greenreader9** [mahtab2003/MOFHY-Lite#101]
**Describe the bug**
Unprepared statements and little, none, or invalid protection causes SQL vulnerabilities. 

Take the following code:

```
$FormData = array(
	'username' => substr(str_shuffle('qwertyuioplkjhgfdsazxcvbnm012345789QWERTYUIOPLKJHGFDSAZXCVBNM'),0,8),
	'password' => substr(str_shuffle('qwertyuioplkjhgfdsazxcvbnm012345789QWERTYUIOPLKJHGFDSAZXCVBNM'),0,16),
	'domain' => $_POST['domain'],
	'email' => $ClientInfo['hosting_client_email'],
	'plan' => $_POST['package']
);
	
/*** Took out some irrelevant stuff here ***/

$sql = mysqli_query($connect,"INSERT INTO `hosting_account`(`account_username`, `account_password`, `account_key`, `account_domain`, `account_status`, `account_date`, `account_for`, `account_sql`) VALUES ('".$Result['username']."','".$FormData['password']."','".$FormData['username']."','".$Result['domain']."','1','".$Result['date']."','".$ClientInfo['hosting_client_key']."','NULL')");
```

Notice how the "plan" and "domain" POST variables are used directly in the INSERT statement. By modifying the POST headers, one can change these variables and unexpected stuff can happen.

**Additional context**
The following resources can help solve this issue:
The use of [prepared statements](https://www.php.net/manual/en/mysqli.quickstart.prepared-statements.php) can divert some attacks.
[Validation of ALL inputs](https://www.sitepoint.com/how-to-protect-your-website-against-sql-injection-attacks/#validateinputstringsontheserverside) that the user may have control over.

**Comment by jaikt** [comment]
`mysql_real_escape_string` will this help?

**Comment by mahtab2003** [comment]
I see..

**Comment by mahtab2003** [comment]
I see..

**Comment by greenreader9** [comment]
Um, this affects more than just that one page, that was only an example. Go though all the code and ctrl f for everything $_POST. Make sure it's all sanitized properly.
