### ISSUE TITLE
email

### ISSUE THREAD

**Issue by jaikt** [mahtab2003/MOFHY-Lite#16]
This is just a doubt. So during signup/reset password, has the verification system changed to direct link verification or still the same old token system? I have not yet updated to v1.0.5.

**Comment by mahtab2003** [comment]
Well every time token change's

**Comment by jaikt** [comment]
I was asking if with the future versions, will the token system be deprecated and a direct email link verification be implemented for new signup and password resets?

**Comment by mahtab2003** [comment]
No

**Comment by jaikt** [comment]
btw, is there any way to contact you personally? I've got some doubts to clear.

**Comment by mahtab2003** [comment]
Yes on whatsapp

**Comment by jaikt** [comment]
Can you share the number

**Comment by mahtab2003** [comment]
+923094428355

**Comment by jaikt** [comment]
i sent a message can you reply?

**Comment by mahtab2003** [comment]
Sure
