### ISSUE TITLE
Want to make some changes

### ISSUE THREAD

**Issue by PiyushYadav007** [mahtab2003/MOFHY-Lite#18]
I wanted to change main domain name with the domain name user requested. Need help

**Comment by greenreader9** [comment]
The code is in "template/view account.PHP" at the bottom, but it is built to show multiple domains, so you will have to edit it to your needs.

**Comment by PiyushYadav007** [comment]
Making changes in template/viewaccount.php will not make any difference I have to store the value of user's domain instead of the main domain so I made changes in function/newaccount.php I replaced $Result['domain'] with $FormData['domain'] in elseif  insert into statement but after uploading the file it is giving me blank page and when I uploaded the correct file too it is showing me blank page. That is why I need help and the second thing user requested domain name should be shown in original mofh too. Consider this is feature request.

**Comment by PiyushYadav007** [comment]
Hey I found the solution
