### ISSUE TITLE
Issue By ItsGamingTube - Didn't show any account on Client Area 

### ISSUE THREAD

**Issue by zeroninefourfour** [mahtab2003/MOFHY-Lite#19]
**Describe the bug**
Create Account Get Something Went Wrong,Didnt show any account on client area

**Screenshots** (9691 is me)
<img width="813" alt="截圖 2021-11-10 下午2 42 57" src="https://user-images.githubusercontent.com/69704016/141063140-8ffd7f9b-0b5b-4e7c-81e8-05d82d7864f4.png">

**Comment by greenreader9** [comment]
Can you print the actual error here and give more details? I have no clue what is actually not working.

**Comment by mahtab2003** [comment]
Maybe the IP address is not whitelisted in MOFH Reseller panel

**Comment by jaikt** [comment]
did you add your client area's server IP address in mofh?

**Comment by zeroninefourfour** [comment]
Umm ask "itsgamingtube*,im not "itsgamingtube"

**Comment by greenreader9** [comment]
Please do not post an issue you cannot replicate. Either close this issue, or find the details we need.
Thanks

**Comment by jaikt** [comment]
Ask "**whoever it is**" to create an issue, right? Why are you asking on behalf of "**whoever it is**"? He would know the issue than you!

**Comment by mahtab2003** [comment]
Ok ok leave it, itsgamingtube is having issue while using github so thus Imloadinguvu help him, that's it!
Ask itsgamingtube to contact me on 0 whatsapp or Gmail. 

> Umm ask "itsgamingtube*,im not "itsgamingtube"

**Comment by ItsGamingTube** [comment]
What's your discord username? I don't use whatsapp (it's the worst app i ever seen) but i can contact you on mail. Tell me your gmail so i can contact you.

**Comment by mahtab2003** [comment]
Admin@nxtshost.eu.org
