### ISSUE TITLE
if account suspended

### ISSUE THREAD

**Issue by jaikt** [mahtab2003/MOFHY-Lite#20]
when the account is suspended from myownfreehost, the status in the client area still didn't change. Anay idea how to fix?

**Comment by mahtab2003** [comment]
It can be fixed using api callback url

**Comment by jaikt** [comment]
how?

**Comment by jaikt** [comment]
i got it. i set the callback url in mofh!

**Comment by greenreader9** [comment]
Correct. Be sure to close the issue if it is solved
