### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by jaikt** [mahtab2003/MOFHY-Lite#22]
Hello There, 
Are there any plans to implement [Google Recaptcha ](https://www.google.com/recaptcha/about/)in future versions? I think it is necessary to prevent bots. I followed this [documentation](https://developers.google.com/recaptcha/docs/faq), but had no luck 😟. **Note**: It's not an issue, just a feature request!

**Comment by mahtab2003** [comment]
I know and it will be implemented
