### ISSUE TITLE
Logout Error - Client Account

### ISSUE THREAD

**Issue by greenreader9** [mahtab2003/MOFHY-Lite#23]
On the second logout attempt, the user is just redirected to the homepage, not logged out.

To replicate:
1. Login to a client account using the login fourm
2. Logout of the account
3. Login to the same account again
4. Attempt to logout

To fix the issue, the cache has to be cleared.

**Comment by mahtab2003** [comment]
Oh

**Comment by jaikt** [comment]
So is this just a trigger, right? Does this cause an error? Or just for information?

**Comment by jaikt** [comment]
I've never experienced such a thing

**Comment by greenreader9** [comment]
>Does this cause an error? Or just for information?

It just never logs the user out.

**Comment by mahtab2003** [comment]
> > Does this cause an error? Or just for information?
> 
> It just never logs the user out.

OK I will see it

**Comment by mahtab2003** [comment]
Every thing is working fine
