### ISSUE TITLE
I am having problem with smtp

### ISSUE THREAD

**Issue by PiyushYadav007** [mahtab2003/MOFHY-Lite#28]
Bro I am using yandex but I am unable to use it on mofhy can anyone help me.

**Comment by jaikt** [comment]
Hi, `@WhiteHacker993`! Can you share the error you are facing? 
- Did you verify your credentials? Sometimes the password or the API key changes itself 😖.
- Make sure to enable <b>Display PHP Errors</b> 
- Or add the following code in any email function e.g `function/signup.php` just after the following line `include __DIR__.'/../handler/EmailHandler.php';`. CODE - `print_r($mail);
exit;`. 
Now the function should print the email content and display errors if found.

**Comment by Lebyy** [comment]
^^ and make sure you are using port `587`

**Comment by PiyushYadav007** [comment]
> Hi, `@WhiteHacker993`! Can you share the error you are facing?
> 
> * Did you verify your credentials? Sometimes the password or the API key changes itself confounded.
> * Make sure to enable Display PHP Errors
> * Or add the following code in any email function e.g `function/signup.php` just after the following line `include __DIR__.'/../handler/EmailHandler.php';`. CODE - `print_r($mail); exit;`.
>   Now the function should print the email content and display errors if found.

Ok I will try

**Comment by PiyushYadav007** [comment]
> ^^ and make sure you are using port `587`

Bro yandex SMTP Port is 465

**Comment by PiyushYadav007** [comment]
Or I think I should try another SMTP service  with maximum number of emails I can sent using SMTP in one day

**Comment by jaikt** [comment]
Yup

**Comment by Lebyy** [comment]
> > ^^ and make sure you are using port `587`
> 
> Bro yandex SMTP Port is 465

Ik but for some weird reason it doesn't work on 465 and does on 587, it's the same case for #6

**Comment by PiyushYadav007** [comment]
Ok I will try

> > > ^^ and make sure you are using port `587`
> > 
> > 
> > Bro yandex SMTP Port is 465
> 
> Ik but for some weird reason it doesn't work on 465 and does on 587, it's the same case for #6

Ok I will try and one more thing I should use app password or real email password?

**Comment by Lebyy** [comment]
> Ok I will try
> 
> > > > ^^ and make sure you are using port `587`
> > > 
> > > 
> > > Bro yandex SMTP Port is 465
> > 
> > 
> > Ik but for some weird reason it doesn't work on 465 and does on 587, it's the same case for #6
> 
> Ok I will try and one more thing I should use app password or real email password?

The password which you used to create the email user.

**Comment by PiyushYadav007** [comment]
Is there any website for checking SMTP working because in a app I am getting problem while checking
![Screenshot_2021-11-16-14-43-59-812_com dcs96 smtp_tester](https://user-images.githubusercontent.com/93871548/141956877-abe6f738-68d7-422f-974a-5da85e7c5236.jpg)
![Screenshot_2021-11-16-14-44-08-517_com dcs96 smtp_tester](https://user-images.githubusercontent.com/93871548/141956893-f9910232-ac1a-4b0c-bc52-835a9359bb29.jpg)

**Comment by PiyushYadav007** [comment]
> > Ok I will try
> > > > > ^^ and make sure you are using port `587`
> > > > 
> > > > 
> > > > Bro yandex SMTP Port is 465
> > > 
> > > 
> > > Ik but for some weird reason it doesn't work on 465 and does on 587, it's the same case for #6
> > 
> > 
> > Ok I will try and one more thing I should use app password or real email password?
> 
> The password which you used to create the email user.

But again I am getting problem

**Comment by PiyushYadav007** [comment]
I am getting email sent successfully but email is not coming

**Comment by PiyushYadav007** [comment]
Currently I am not using SSL certificate

**Comment by Lebyy** [comment]
Is your email activated? You need to login into that email from
mail.yandex.com and activate it.

**Comment by PiyushYadav007** [comment]
> Is your email activated? You need to login into that email from mail.yandex.com and activate it.

Bro it is active

**Comment by jaikt** [comment]
Did you configure the send as email first of all?

**Comment by WhiteHacker993** [comment]
> Is your email activated? You need to login into that email from mail.yandex.com and activate it.

It is active

**Comment by PiyushYadav007** [comment]
> Did you configure the send as email first of all?

How to do that?

**Comment by PiyushYadav007** [comment]
Even with the correct SMTP information mail is not sending

**Comment by jaikt** [comment]
I too faced the problem! Sendinblue, Maijet, Senclean didn't work in my case. So I moved my gsuite account's SMTP server. This is not a MOFHY issue. It's some sort of compatibility issue with PHPMailer (in this case we have an old version with MOFHY).

**Comment by PiyushYadav007** [comment]
I have two domains on both I am using mofhy but one is working correctly and another one is not even with the same SMTP settings

**Comment by greenreader9** [comment]
I have used Yandex before, and it look me almost 2 months to get email to not go to spam. I recommend using a different provider.

**Comment by PiyushYadav007** [comment]
Ok but I am saying that I have 2 domains. One the first one it is working but on second one is not with same SMTP settings

**Comment by greenreader9** [comment]
Again, this problem with the provider and your setup, not the script. Ask your email provider for help.

**Comment by PiyushYadav007** [comment]
Hey guys look I found something when I tried to send email using this script my mail goes directly into mail folder not in spam but with mofhy it is going in spam I am not saying that it is mofhy's problem but jut have a look at this and think can we use this in mofhy.

**Comment by PiyushYadav007** [comment]
<!DOCTYPE html>
<html>
  
<head>
  <title>Send Mail</title>
  <script src=
    "https://smtpjs.com/v3/smtp.js">
  </script>
  
  <script type="text/javascript">
    function sendEmail() {
      Email.send({
        Host: "smtp.gmail.com",
        Username: "example@gmail.com",
        Password: "password",
        Port: 587,
        To: ' songsd269@gmail.com',
        From: "example@gmail.com",
        Subject: "Sending Email using javascript",
        Body: "Well that was easy!!",
      })
        .then(function (message) {
          alert("mail sent successfully")
        });
    }
  </script>
</head>
  
<body>
  <form method="post">
    <input type="button" value="Send Email" 
        onclick="sendEmail()" />
  </form>
</body>
  
</html>

**Comment by PiyushYadav007** [comment]
[New.zip](https://github.com/mahtab2003/MOFHY-Lite/files/7573873/New.zip)

**Comment by mahtab2003** [comment]
Well because in mofhy From parameter is used the mail goes to spam box it can be fixed by generating gpg encryption key in cpanel

**Comment by PiyushYadav007** [comment]
How to do that?

**Comment by mahtab2003** [comment]
In emailhanlder.php file remove $mail->From parameter and its value

**Comment by zeroninefourfour** [comment]
yandex smtp port is 587.
<img width="492" alt="截圖 2021-11-23 下午7 49 14" src="https://user-images.githubusercontent.com/69704016/143019063-30946428-2c34-485b-ac46-0deb8170acbb.png">
.

**Comment by mahtab2003** [comment]
If the issue is solved please close this issue
