### ISSUE TITLE
Why verifying emails going in spam?

### ISSUE THREAD

**Issue by PiyushYadav007** [mahtab2003/MOFHY-Lite#29]
Why verifying emails are going in spam?

**Comment by greenreader9** [comment]
Because of the SMTP service you are using. This has nothing to do with MOFHY and everything to o with your SMTP setup.

**Comment by Lebyy** [comment]
Add a dkim key to your domain probably.

**Comment by jaikt** [comment]
Hi @WhiteHacker993!
This is not an issue produced by MOFHY. It all depends on your domain and SMTP server's IP reputation and many factors. You can test your domain and server's IP - https://talosintelligence.com/reputation_center/

**Comment by PiyushYadav007** [comment]
Ok thanks
