### ISSUE TITLE
NOT BUG! Account Creation Question

### ISSUE THREAD

**Issue by greenreader9** [mahtab2003/MOFHY-Lite#30]
When a user creates an account, they are asked to create a password. Why is that password never using? What is the point is even asking the user to create one? I am updating my installation to actually make sure of that field, but why was it created in the first place?

**Comment by mahtab2003** [comment]
Well it just got client to feel like infinityfree but it doesn't have to do anything

**Comment by jaikt** [comment]
I removed the required tag and it's classes and put the placeholder like infinityfree one's

**Comment by PiyushYadav007** [comment]
> I removed the required tag and it's classes and put the placeholder like infinityfree one's

Does this mean that in your version account password will work as cpanel password?

**Comment by PiyushYadav007** [comment]
Ok thanks
