### ISSUE TITLE
Something Went Wrong

### ISSUE THREAD

**Issue by zeroninefourfour** [mahtab2003/MOFHY-Lite#32]
**Describe the bug**
Ummm,Cant Create Account,Getting Somethin Went Wrong Error.
IP Already Set
Callback too

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browse : Safari
 - Version: 12.0.1

**Smartphone (please complete the following information):**
 - Device: Realme XT
 - OS: Android,Realme UI
 - Browser : Chrome
 - Version Android 10
<img width="614" alt="截圖 2021-11-23 下午7 39 49" src="https://user-images.githubusercontent.com/69704016/143017879-d6f55e98-1f25-4544-9f80-758ae644ab1f.png">

Account Created But CA Didnt Show.

**Comment by greenreader9** [comment]
Reinstall MOFHY. Everything is working for me

**Comment by ItsGamingTube** [comment]
Same error for me.

**Comment by ItsGamingTube** [comment]
Also mobile is bad lel you can't play red dead redemption or grand theft auto or any other cool games

**Comment by greenreader9** [comment]
Please stay on topic

**Comment by zeroninefourfour** [comment]
> Please stay on topic

The Problem On mOFHY-Lite Dev.,Release Dont Have This Problem

**Comment by mahtab2003** [comment]
Sorry that was my mistake😜.
Please reinstall mofhy lite to work correctly.

**Comment by zeroninefourfour** [comment]
oooooooooooooooooooooooOOOOk thanks

**Comment by zeroninefourfour** [comment]
> Also mobile is bad lel you can't play red dead redemption or grand theft auto or any other cool games same on mac lol mac is the worst pc you can ever have

😕

**Comment by zeroninefourfour** [comment]
> Sorry that was my mistake😜.
> Please reinstall mofhy lite to work correctly.

ummm still not work,I update function folder.

**Comment by mahtab2003** [comment]
You need to update database as well
