### ISSUE TITLE
Something Went Wrong pls help

### ISSUE THREAD

**Issue by ItsGamingTube** [mahtab2003/MOFHY-Lite#33]
**Describe the bug**
It's a weird bug 

**To Reproduce**
1. Install Mofhy Lite on your myownfreehost.net hosting and upload the files on the mofh servers using ftp (filezilla is the best)
2. Complete everything (put byethost.net db servers if you use cloudflare like me)
3. Create a temp alt account (mail.tm for the best temp mail) + SFTP from yandex
4. You will see an error when trying to create a new account

**Expected behavior**
You will get Something went Wrong

**Screenshots**
I don't have time now cuz im playing red dead redemption 2 so no

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bit 21H2 update november 2021
 - Specs: 32GB ram Nvidia 1070 i9 TMP 2.0 security custom bios with UEFI support and a 512GB SSD
 - Browser Firefox 94.0.2 And Edge 21H2 updated
 - Version 1.0.5
 (I will delete the mobile field cuz mobile is bad lol)

**Additional context**
Nothing here. Just a gay text (jk lol).

**Comment by greenreader9** [comment]
The something went wrong error mainly occurs if you have not set up the API correctly. Everything works fine for me, so it is not a code issue.

**Comment by mahtab2003** [comment]
Sorry that was my mistake😜.
Please reinstall mofhy lite to work correctly.
