### ISSUE TITLE
MOFH API Down  Security Issues

### ISSUE THREAD

**Issue by zeroninefourfour** [mahtab2003/MOFHY-Lite#34]
I found another Security Issue,If MOFH API Down. Other User Can See Your Token.
<img width="1371" alt="截圖 2021-11-27 上午10 00 37" src="https://user-images.githubusercontent.com/69704016/143664669-ca7a5878-1325-4092-b758-db51a994ba0f.png">

**Comment by mahtab2003** [comment]
I will try to fix it

**Comment by mahtab2003** [comment]
Sorry this bug cannot be fixed

**Comment by Lebyy** [comment]
> Sorry this bug cannot be fixed

Can't you just maybe throw a custom error instead?

**Comment by mahtab2003** [comment]
I will try
