### ISSUE TITLE
Admin Panel Feature Not Completed

### ISSUE THREAD

**Issue by zeroninefourfour** [mahtab2003/MOFHY-Lite#35]
I Found a... 🤔 ....Admin Panel Feature Is Uncomplete...
View Account Active Account,Deactive Account Feature Is Missing.
View Account only has 3 buttons, FTP , cP , Open Ticket, how does admin open ticket for admin>?????????????>?

**Comment by jaikt** [comment]
does i matter>

**Comment by zeroninefourfour** [comment]
idk

**Comment by mahtab2003** [comment]
Ok ok I will fix it

**Comment by mahtab2003** [comment]
Completed
