### ISSUE TITLE
ssl not creating.

### ISSUE THREAD

**Issue by jaikt** [mahtab2003/MOFHY-Lite#37]
the create ssl is not working

`function/NewSSL.php` is printing the array not processing the request

**Comment by mahtab2003** [comment]
Hmm

**Comment by greenreader9** [comment]
That issue was already fixed (I think, maybe I just unintentionally fixed it myself).Try re-installing MOFHY

**Comment by jaikt** [comment]
sorry, the api credentials were wrong!
