### ISSUE TITLE
Missing /admin/settings.php

### ISSUE THREAD

**Issue by rexluciano** [mahtab2003/MOFHY-Lite#38]
I downloaded the source, then installed it on my reseller hosting site, then I tried to edit client account and that settings.php is missing on admin/settings.php

**Comment by greenreader9** [comment]
So download that file and install it.

**Comment by mahtab2003** [comment]
> I downloaded the source, then installed it on my reseller hosting site, then I tried to edit client account and that settings.php is missing on admin/settings.php

Sorry that was my mistake I will upload it once it is edited

**Comment by rexluciano** [comment]
Sorry, that was not in admin folder. It's on client page

**Comment by mahtab2003** [comment]
Oh

**Comment by rexllc** [comment]
Deprecated: Array and string offset access syntax with curly braces is deprecated in modules/whois/whois.php on line 224

**Comment by greenreader9** [comment]
So witch file is missing?

**Comment by mahtab2003** [comment]
Problem solved
