### ISSUE TITLE
Please Update Your Security Policy. I'd like to report a security issue (Critical)

### ISSUE THREAD

**Issue by PlanetTheCloud** [mahtab2003/MOFHY-Lite#48]
**Describe the bug**
Security Policy is incomplete.

**To Reproduce**
1. Go to https://github.com/mahtab2003/MOFHY-Lite/security/policy

**Expected behavior**
A way for me to report security vulnerabilities directly.

**Screenshots**
Does not matter

**Desktop (please complete the following information):**
Does not matter

**Smartphone (please complete the following information):**
Does not matter

**Additional context**
None

**Comment by mahtab2003** [comment]
Security Policy updated

**Comment by PlanetTheCloud** [comment]
Thank you
