### ISSUE TITLE
[Critical] Logic Bomb leading to Unauthorized Account Access

### ISSUE THREAD

**Issue by PlanetTheCloud** [mahtab2003/MOFHY-Lite#53]
This issue has been disclosed privately to the author (on Jan 8th) but it's taking too long to be fixed.

The following text are mostly copied and pasted from the email:
I noticed the use of LEFSESS cookie to remember a user login. This can easily be manipulated and can be used to take over someone else's account just by knowing their email address. If you know someone's email address, you can base64 encode it and set it as the cookie.
![unnamed](https://user-images.githubusercontent.com/35788716/149607397-24964cba-9429-4a99-9002-2e577d541e40.png)
This screenshot shows that the vulnerability works.
On the left-hand side is the Client Area accessed by manually logging in.
On the right-hand side is the Client Area accessed by just editing the cookie for LEFSESS using this website https://www.base64encode.org/ and appending "%3D%3D" at the end of the encoded result to the cookie. This is a very critical problem and must be prioritized.

Affected files:
- src/function/Login.php (set cookie part).
- src/handler/CookieHandler.php (entire logic).
- And other files that handle the ADMIN cookies.

**Comment by santydesignscr** [comment]
Ohhhh

**Comment by santydesignscr** [comment]
I use this cookie to reidrect yo the client area when is logged, I have expanded this vulnerability in my site

**Comment by PlanetTheCloud** [comment]
> I use this cookie to reidrect yo the client area when is logged, I have expanded this vulnerability in my site

I see... it would be nice if you can implement a fix and create a PR here as well.

**Comment by santydesignscr** [comment]
Yes I Will to do that soon

**Comment by mahtab2003** [comment]
Fixed

**Comment by PlanetTheCloud** [comment]
![image](https://user-images.githubusercontent.com/35788716/149609776-9e8d6537-6fe3-4ebe-9b14-e2e5a5052872.png)
NOT FIXED! THIS IS EVEN WORSE! Using `hosting_client_key` means they don't even have to guess the email address, just do a brute force of numbers from 000001 until 999999!

**Comment by PlanetTheCloud** [comment]
Beware, this might even be a flaw where the randomized numbers might conflict and returned "account already exists", confusing the user.
![image](https://user-images.githubusercontent.com/35788716/149609935-fc0b7f75-1830-41c4-9ea7-aa3161d65f71.png)

**Comment by PlanetTheCloud** [comment]
The correct way to implement this is to create a new table storing a list of "remember tokens" with expiration time and user ID.

When a user makes a request with the token, check it in the database (hash the token in the database for added security) and check if the token had expired. If the token is still valid, log the user in using the ID stored in the database.

The Remember token must be generated from random and cryptographically secure generator. Preferably longer strings.

**Comment by santydesignscr** [comment]
I will to try to fix in my site and will to create PR request

**Comment by BastelPichi** [comment]
Just base64 hash up something like `email|password`. Super easy to handle later.

**Comment by greenreader9** [comment]
@PlanetTheCloud, is @mahtab2003 fix ok, or should it be done differently?

**Comment by mahtab2003** [comment]
> @PlanetTheCloud, is @mahtab2003 fix ok, or should it be done differently?

Like?
