### ISSUE TITLE
[Critical] XSS Vulnerability

### ISSUE THREAD

**Issue by PlanetTheCloud** [mahtab2003/MOFHY-Lite#54]
This issue has been disclosed privately to the author (on Jan 8th) but it's taking too long to be fixed.

The following text is mostly copied and pasted from the email:
On src/template/ViewKnowledgebase.php line 4, you are using $_GET without any sanitation such as htmlspecialchars (https://www.php.net/manual/en/function.htmlspecialchars.php) which caused an XSS vulnerability. I only spot this one area, but there might be more. 
![unnamed](https://user-images.githubusercontent.com/35788716/149607543-9f51b9fa-dc30-49f1-a195-0bf638f38118.png)
(XSS can be used to send requests on behalf of the user, so don't take this lightly)

**Comment by santydesignscr** [comment]
Bro, whrite me to contacto@santydesigns.com And I will fix those vulnerabilities, except for the cookie thing because I have no idea what to do in that case.

**Comment by PlanetTheCloud** [comment]
> Bro, whrite me to [contacto@santydesigns.com](mailto:contacto@santydesigns.com) And I will fix those vulnerabilities, except for the cookie thing because I have no idea what to do in that case.

There's no need for private emails anymore. We can discuss it here. If you plan on to fix the vulnerabilities, it would be nice to create a Pull Request here so others may use them as well.

**Comment by santydesignscr** [comment]
Yes but, but I'm going to do it tomorrow because it's very late in my country

**Comment by PlanetTheCloud** [comment]
> Yes but, but I'm going to do it tomorrow because it's very late in my country

No worries, you can make a PR request at any time!

**Comment by santydesignscr** [comment]
😆 ok

**Comment by santydesignscr** [comment]
I have fixed?, see my pull request

**Comment by mahtab2003** [comment]
Fixed
