### ISSUE TITLE
Any Button Navigates to srcadmin/filename.php

### ISSUE THREAD

**Issue by finley541** [mahtab2003/MOFHY-Lite#58]
When I click an navigation button, it sends me to the page but without a / between src and admin. Only provides a 404 error (as expected) Any help would be appreciated.

**Comment by santydesignscr** [comment]
Bro this repository will not receive any more updates, the developer has discontinued the project, I recommend [MOFHY Pro](http://getmofhy.eu.org), the license only costs $5 per year

**Comment by santydesignscr** [comment]
> When I click an navigation button, it sends me to the page but without a / between src and admin. Only provides a 404 error (as expected) Any help would be appreciated.

That is a configuration error, in the clientarea URL you have to put a / at the end of the url (https://yoursite.com/), it always has to end with a /

**Comment by santydesignscr** [comment]
That repository have an syntax error in /function/NewTicket.php I have fixed in [my repository](https://github.com/santydesignscr/MOFHY-Lite-Multi-Language), there is 3 builds: English (Normal), Spanish (MOFHY Lite translated to Spanish) and Multi (MOFHY Lite in 5 languages).

**Comment by PlanetTheCloud** [comment]
Holy sh*t..... so MOFHY Lite is not receiving any updates?

**Comment by PlanetTheCloud** [comment]
I sure feel bad for all the sites that use this and have the flaws I've reported.
Also, I really do hope the PRO (since it is closed source) does not have more hidden issues and logic bombs.

**Comment by BastelPichi** [comment]
> I sure feel bad for all the sites that use this and have the flaws I've reported. Also, I really do hope the PRO (since it is closed source) does not have more hidden issues and logic bombs.

I think the Pro version isn't that much different. Check out here: [http://getmofhy.eu.org](http://getmofhy.eu.org)

**Comment by santydesignscr** [comment]
I think the same, but keep in mind that maintaining an open source project can be a bit complicated for a developer, MOFHY Pro comes with quite a few features that are good, and security has been greatly improved

**Comment by santydesignscr** [comment]
I use MOFHY Pro and I am very satisfied, the only problem is that I could not update due to a license error that will be fixed very soon.

**Comment by BastelPichi** [comment]
Generally, even the Pro isnt more really maintained. For example getmofhy.eu.org has no SSL certificate anymore.

**Comment by santydesignscr** [comment]
That's true, but if I think it's worth it, then this is the only client area for MOFH that I know of.

**Comment by santydesignscr** [comment]
Is there any other?

**Comment by BastelPichi** [comment]
> Is there any other?

No, not that I know. However, coding an own Client Area isn't that much work. I think you can get something basic in 10h easely done.

**Comment by santydesignscr** [comment]
I only ask

**Comment by santydesignscr** [comment]
Ohhhh

**Comment by greenreader9** [comment]
From experiencing the pro version, many of these vulnerabilities, especially the logic bombing one, is still present. I do not recommend paying for security lacking software. 

Take the free version, and fix the errors PlanetTheCloud found, that's the only right way to do this.

**Comment by santydesignscr** [comment]
Ok

**Comment by BastelPichi** [comment]
> From experiencing the pro version, many of these vulnerabilities, especially the logic bombing one, is still present. I do not recommend paying for security lacking software.
> 
> Take the free version, and fix the errors PlanetTheCloud found, that's the only right way to do this.

Agree.

**Comment by Lebyy** [comment]
Will anyone create a maintained fork which fixes the security vulnerabilities and maybe update it?

**Comment by BastelPichi** [comment]
Well... I can do a bit, but dont really wanna spend that much time on it as Im currecntly creatinbg my own client area. So if noone else wants I can, but Im not really the first choice.

**Comment by santydesignscr** [comment]
I have a repository and currently I can continue to maintain it but I cannot always be available, I need help

**Comment by BastelPichi** [comment]
> I have a repository and currently I can continue to maintain it but I cannot always be available, I need help

I think it would be better to seperate the Multi lang and the normal english version for now.

**Comment by santydesignscr** [comment]
They are separated, that's why there are several folders

**Comment by BastelPichi** [comment]
> They are separated, that's why there are several folders

Are they in the same repository?

**Comment by santydesignscr** [comment]
Yes, it is because I want to have all 3 versions

**Comment by santydesignscr** [comment]
English, Spanish and Multi

**Comment by BastelPichi** [comment]
Please move conversation to here: https://github.com/NXTS-Developers/MOFHY-Lite/issues/59
So that the creator of this issue isnt getting spammed.

**Comment by BastelPichi** [comment]
Please move conversation to here: https://github.com/NXTS-Developers/MOFHY-Lite/issues/59
So that the creator of this issue isnt getting spammed.

**Comment by finley541** [comment]
> Bro this repository will not receive any more updates, the developer has discontinued the project, I recommend [MOFHY Pro](http://getmofhy.eu.org), the license only costs $5 per year

That's unfortunate
