### ISSUE TITLE
Disscusion: Maintaining the Project

### ISSUE THREAD

**Issue by BastelPichi** [mahtab2003/MOFHY-Lite#59]
Moved.

**Comment by santydesignscr** [comment]
Ok, who wants to support the project to keep MOFHY Lite?

**Comment by santydesignscr** [comment]
https://github.com/santydesignscr/MOFHY-Lite-Multi-Language/

**Comment by greenreader9** [comment]
MOFHY-Lite is going to need a big security update, not really something I have time for at the moment. They entire key system needs to be redone.

**Comment by santydesignscr** [comment]
I know and that's why I need help, but in reality this system is not very big

**Comment by greenreader9** [comment]
I will have a lot more free time to work on it after the 12th of February. In the meantime, I am trying to compile a list of everything that needs to be fixed. Would love to partner with you later if the issues are still not resolved!

**Comment by jaikt** [comment]
> I know and that's why I need help, but in reality this system is not very big

I can be of any help maybe.

**Comment by Lebyy** [comment]
> https://github.com/santydesignscr/MOFHY-Lite-Multi-Language/

I suggest moving the different languages to branches created for each language since it's easier to contribute and will look much cleaner.

**Comment by BastelPichi** [comment]
> > https://github.com/santydesignscr/MOFHY-Lite-Multi-Language/
> 
> I suggest moving the different languages to branches created for each language since it's easier to contribute and will look much cleaner.

yeah. or just seperate them to different repos.

**Comment by santydesignscr** [comment]
It seems fine to me but I would like all languages ​​to have the same updates, I will separate it in different branches

**Comment by jaikt** [comment]
Or, create different repo's with language name in name.

**Comment by santydesignscr** [comment]
Yes but I prefer the branches

**Comment by jaikt** [comment]
I think all should stick to one type. I vote for different repo's. Also, I will be releasing the version of MOFHY with a new theme (instead of halfmoon). Thanks!

**Comment by santydesignscr** [comment]
Ohhh

**Comment by jaikt** [comment]
But the security flaw still remains.

**Comment by BastelPichi** [comment]
I think we should care about the Security in a seperate branch on maybe an Organisation first, then everybody can maintain their forks of MOFHY Lite.

**Comment by jaikt** [comment]
ok i'll create an org?

**Comment by BastelPichi** [comment]
Yeah go on if you want.

**Comment by santydesignscr** [comment]
Will my code be used?

**Comment by BastelPichi** [comment]
What modifications did you do to it?

**Comment by santydesignscr** [comment]
Multi Language, instead of csr it only asks for a domain when creating an ssl

**Comment by santydesignscr** [comment]
https://github.com/users/santydesignscr/projects/1

**Comment by santydesignscr** [comment]
I Will to create 3 repositories and add the code of each build

**Comment by BastelPichi** [comment]
Anyone created a orga yet?

**Comment by greenreader9** [comment]
> I think we should care about the Security in a seperate branch on maybe an Organisation first, then everybody can maintain their forks of MOFHY Lite.

I agree, all security issues need to be fixed BEFORE any UI changes are made. Lets take Santiago's English build into a new respiratory and make changes to it. Once all security issues are taken care of, then we can each fork it and change it to our liking.

**Comment by greenreader9** [comment]
> Anyone created a orga yet?

I will create one now

**Comment by BastelPichi** [comment]
ok.

**Comment by santydesignscr** [comment]
I am uploading the files to repos

**Comment by greenreader9** [comment]
What should I call it?

I will have it done in an hour, I need my other PC

@santydesignscr, can you have the files ready to upload? Ill send you the link once I set the org, respiratory, and permissions setup.

**Comment by BastelPichi** [comment]
I can also do it if thats easyer.

**Comment by greenreader9** [comment]
On seccond though, I might be able to do it now. What should I call it?

**Comment by BastelPichi** [comment]
I now did on. i called it "MOFHY-Lite"

**Comment by BastelPichi** [comment]
invites sent.

**Comment by santydesignscr** [comment]
https://github.com/santydesignscr/MOFHY-Lite-English

**Comment by BastelPichi** [comment]
@greenreader9  Allright then we take yours

**Comment by greenreader9** [comment]
Sorry, I diden't notice you made one, oops. 

I sent an invite, let me know if you did not get it.

Since I am on a chromebook at the moment, I don't have access to CMD or GitHub Desktop, so I cant upload the files.

**Comment by BastelPichi** [comment]
I can upload them. But you can also upload files via Web.

**Comment by santydesignscr** [comment]
Yes

**Comment by greenreader9** [comment]
> I can upload them. But you can also upload files via Web.

But it does not accept folder, or am I just doing it wrong?

**Comment by BastelPichi** [comment]
It was too many folders. WHo uploaded the files?

**Comment by greenreader9** [comment]
Looks good now. Lets move that chat over to the new respiratory.
https://github.com/MOFH-Dev/MOFHY-Lite/discussions/2

**Comment by santydesignscr** [comment]
I have created the repos

**Comment by santydesignscr** [comment]
see my profile

**Comment by santydesignscr** [comment]
Why i do?

**Comment by santydesignscr** [comment]
Repos moved

**Comment by santydesignscr** [comment]
I already transferred everything, now what to do?

**Comment by greenreader9** [comment]
Everything is private on your profile. Everything has been moved to the new org. I sent you an invation, did you get it?

**Comment by santydesignscr** [comment]
Yes

**Comment by santydesignscr** [comment]
See the org

**Comment by santydesignscr** [comment]
All of the repos have moved

**Comment by santydesignscr** [comment]
Move the Discussion to here https://github.com/MOFH-Dev/MOFHY-Lite-English/discussions/2

**Comment by BastelPichi** [comment]
moved ^^
