### ISSUE TITLE
[Critical] Logic Bomb: Change admin settings without login

### ISSUE THREAD

**Issue by PlanetTheCloud** [mahtab2003/MOFHY-Lite#60]
The check to ensure a user is logged in is performed but not enforced. The user may seem to be redirected away but the underlying code is still executed. This caused requests to still be processed. I've tested it on the Admin Change Area Settings but this will work on any other functions that modify the database state and accept POST or GET requests.

BEFORE:
![image](https://user-images.githubusercontent.com/35788716/150486846-58f6ba0f-896e-408c-b6ba-fdb0e30ad81c.png)

AFTER:
![image](https://user-images.githubusercontent.com/35788716/150486870-10f816f3-e2b6-47b5-a2a2-f8ae59f36857.png)

The request:
![image](https://user-images.githubusercontent.com/35788716/150486898-4602eb7b-695b-454e-88f1-b638e6c90f0f.png)

Reference and how to solve: https://www.php.net/manual/en/function.header.php

This might be the last report I'll make in this repository. I stumbled upon this flaw when checking the admin's session handler.

**Comment by mahtab2003** [comment]
Ok

**Comment by zeroninefourfour** [comment]
????? ????? ???? ?? ??? ???? ?? ???! ?????? ?? ???!

**Comment by PlanetTheCloud** [comment]
> ????? ????? ???? ?? ??? ???? ?? ???! ?????? ?? ???!

??????????????????????????????????????????????????? what

**Comment by PlanetTheCloud** [comment]
Is this fixed?

**Comment by mahtab2003** [comment]
i dont think so

**Comment by mahtab2003** [comment]
Check now I changed code a bit maybe it should be fixed.

**Comment by PlanetTheCloud** [comment]
> 

When you fix an issue, you can put on the commit summary "Fix #<issue number>" so it will automatically tag this.

**Comment by mahtab2003** [comment]
Ok
