### ISSUE TITLE
Add a feature to remove account verification

### ISSUE THREAD

**Issue by tanguy-fgl** [mahtab2003/MOFHY-Lite#61]
Please add this feature, because on my host I can't use php send mail feature

**Comment by mahtab2003** [comment]
Oh it's pretty easy to remove

**Comment by greenreader9** [comment]
PHP mail() is not used, SMTP is. If you host does not allow SMTP, you really should find a new one.

**Comment by mahtab2003** [comment]
If you don't want the user to verify account you just need to change account status from 0 to 1 in function/signup.php
