### ISSUE TITLE
My mail sending is not working

### ISSUE THREAD

**Issue by Gouravyadavyt** [mahtab2003/MOFHY-Lite#65]
I use this script in 
Https://account.easyteach.tk/
Every thing is fine but mail sending system is not working
I tried Gmail ,own server , mail gun SMTP 
Please solve

**Comment by greenreader9** [comment]
Gmail SMTP works just fine. You need to use 2FA and create an APP Password though.

**Comment by jaikt** [comment]
Check your error log. Also the domain is not valid.

**Comment by Gouravyadavyt** [comment]
Ok 2FA on karna hai ya off

**Comment by jaikt** [comment]
On

**Comment by Gouravyadavyt** [comment]
Try kar liya nhi hoo pa rha hai

**Comment by mahtab2003** [comment]
I see your web hosting server block outgoing emails from external smtp servers

**Comment by Gouravyadavyt** [comment]
And it also not working in enternal server

**Comment by jaikt** [comment]
Check with your host if some ports are blocked or etc.

**Comment by Gouravyadavyt** [comment]
My own SMTP are work on any script like wp whmcs and etc but why this problem

**Comment by Gouravyadavyt** [comment]
> Check with your host if some ports are blocked or etc.

And I check your website royalty free superb👍

**Comment by jaikt** [comment]
> And I check your website royalty free superb👍

Thanks!

**Comment by mahtab2003** [comment]
Is it problem resolved?

**Comment by Gouravyadavyt** [comment]
No . I just remove verification process 
Because of this

**Comment by mahtab2003** [comment]
Oh

**Comment by Gouravyadavyt** [comment]
Can you send mail without phpmailer
So please do it request

**Comment by mahtab2003** [comment]
Yes it can be send mail() in php
