### ISSUE TITLE
Wrong tld

### ISSUE THREAD

**Issue by Aleperix** [mahtab2003/MOFHY-Lite#7]
Hello, sorry but I have created a new hosting account with a test user, I have chosen a domain extension that I have added to my panel (.fuxy.ml) but for some reason, I create the account with a domain name with characters random apparently and also with the main extension. And it's not what I want.

Would you dare to access my website and try it out for yourself?

I had already installed Santi's version and the exact same thing happened to me.

https://img.aoli.ml/mcDUehO.png

**Comment by Aleperix** [comment]
Also the created site redirects me to this.

https://img.aoli.ml/z4IoSEP.png

The truth is I don't know why it happens.

Also, the password is not the same as the one requested in the form. It was created randomly.

**Comment by mahtab2003** [comment]
If you go to the test use account and access it's cpanel in details in bottom of the page you will find a domain name with the label called Main Domain and it's value will be random if you want your clients registered domain I am working on it

**Comment by Aleperix** [comment]
> If you go to the test use account and access it's cpanel in details in bottom of the page you will find a domain name with the label called Main Domain and it's value will be random if you want your clients registered domain I am working on it

Oh good, and by when could that be implemented?

I am testing the "main" domain and it is not accessing the actual website.

I don't understand why it doesn't work.

I would appreciate if you could try my site and give me a diagnosis.

**Comment by mahtab2003** [comment]
> > If you go to the test use account and access it's cpanel in details in bottom of the page you will find a domain name with the label called Main Domain and it's value will be random if you want your clients registered domain I am working on it
> 
> Oh good, and by when could that be implemented?
> 
> I am testing the "main" domain and it is not accessing the actual website.
> 
> I don't understand why it doesn't work.
> 
> I would appreciate if you could try my site and give me a diagnosis.

Activate my account from admin panel

**Comment by mahtab2003** [comment]
> Also the created site redirects me to this.
> 
> https://img.aoli.ml/z4IoSEP.png
> 
> The truth is I don't know why it happens.
> 
> Also, the password is not the same as the one requested in the form. It was created randomly.

Because using a random password is safe the using a custom password each account must have unique password, username, main domain
Main while the main domain is used to verify the authority of a person who is using free hosting service if a use delete all his domain the system will treat him the way he was before because main domain

**Comment by Aleperix** [comment]
> > > If you go to the test use account and access it's cpanel in details in bottom of the page you will find a domain name with the label called Main Domain and it's value will be random if you want your clients registered domain I am working on it
> > 
> > 
> > Oh good, and by when could that be implemented?
> > I am testing the "main" domain and it is not accessing the actual website.
> > I don't understand why it doesn't work.
> > I would appreciate if you could try my site and give me a diagnosis.
> 
> Activate my account from admin panel

I have already activated your account, I had to do it from the database because it did not appear in the customer list as I did not have the account active.



> > Also the created site redirects me to this.
> > https://img.aoli.ml/z4IoSEP.png
> > The truth is I don't know why it happens.
> > Also, the password is not the same as the one requested in the form. It was created randomly.
> 
> Because using a random password is safe the using a custom password each account must have unique password, username, main domain Main while the main domain is used to verify the authority of a person who is using free hosting service if a use delete all his domain the system will treat him the way he was before because main domain

Sure, but the domain that I enter in the form does not work at all. It is as if it was of no use to itself. But when you want to register it again, it takes it as if it were already registered.

**Comment by greenreader9** [comment]
That's how it's supposed to work. The "Main Domain" (jumbled mess of￼ characters) is just there for verification. It will always show the suspended page. To view the actual domain that the website is on, you have to open the control panel and view the domains section. The actual domain may be displayed in the client area in the future, but that feature is still under development.

**Comment by mahtab2003** [comment]
Yes
