### ISSUE TITLE
[BUG] MySQL problems after updating 1.0.5 to 1.0.6

### ISSUE THREAD

**Issue by tanguy-fgl** [mahtab2003/MOFHY-Lite#73]
Hi, I updated my MOFHY Lite to 1.0.6 and login and other data of the previous version aren't read on the database. So I can't login to my account and my customers can't manage their services correctly. Please help to fix this bug.

**Comment by mahtab2003** [comment]
Yes password structure had been changed

**Comment by greenreader9** [comment]
You will have to reset the password of every client, or code in a way to accept the sha1 hash of a password, but change it to an sha256 one.
