### ISSUE TITLE
[FEATURE REQUEST] Auto add a dot when sub-domain is selected

### ISSUE THREAD

**Issue by tanguy-fgl** [mahtab2003/MOFHY-Lite#74]
Hi, can it's possible to aut add a dot to the sub-domain selection
![image](https://user-images.githubusercontent.com/44116544/153228210-c6d78c2a-12b0-4092-86fd-88222a2bbcb4.png)
![image](https://user-images.githubusercontent.com/44116544/153228339-6c56aed5-471d-486e-a148-70af89ac23d7.png)
![image](https://user-images.githubusercontent.com/44116544/153228388-30621792-a5fc-4b75-afca-03e266fc27fa.png)
I'm sorry but I translated MOFHY in french, but when I choose a name for a sub domain, MOFHY does'nt add a dot between the sub-domain and the main domain of the host

**Comment by mahtab2003** [comment]
Si i will update it.

**Comment by mahtab2003** [comment]
Si i will update it.

**Comment by mahtab2003** [comment]
Si i will update it.

**Comment by jaikt** [comment]
You can add a dot before the domain in your admin panel.

**Comment by mahtab2003** [comment]
Fixed
