### ISSUE TITLE
qwetyuiop idk title

### ISSUE THREAD

**Issue by zeroninefourfour** [mahtab2003/MOFHY-Lite#77]
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: Error while connecting to the host in /owo/owo/owo/owo/public/owo/modules/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0

**Comment by mahtab2003** [comment]
?? What can i do in this case?

**Comment by zeroninefourfour** [comment]
idk

**Comment by mahtab2003** [comment]
Then?? What is it dear??

**Comment by greenreader9** [comment]
We can't help you if you don't give us more details on the problem.

**Comment by zeroninefourfour** [comment]
umm,i clicked validate button and it give me this errrrr!!!
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: Error while connecting to the host in /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0 /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError() #2 /home/030/domains/managedomain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: Error while connecting to the host in /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0 /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError() #2 /home/030/domains/managedomain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish() #3 /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() #4 /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Ha in /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210GuzzleHttp\Handler\CurlFactory::finish() #3 /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() #4 /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Ha in /home/030/domains/manage.domain.tld/public/user/modules/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210

**Comment by zeroninefourfour** [comment]
oooo!!! https://panel.myownfreehost.net/xml-api/ working but with port. not working!

**Comment by mahtab2003** [comment]
Hmm....

**Comment by mahtab2003** [comment]
Port is having ssl err
