### ISSUE TITLE
Domain Section Does Not Work

### ISSUE THREAD

**Issue by greenreader9** [mahtab2003/MOFHY-Lite#8]
As title says

Client Area:
![Screenshot 2021-10-18 4 41 15 PM](https://user-images.githubusercontent.com/75644395/137810728-d6f5329f-b414-4ed0-b3c2-b07a585ada48.png)

Proof that account has a domain:
![Screenshot 2021-10-18 4 42 18 PM](https://user-images.githubusercontent.com/75644395/137810898-68eeb470-589f-45c2-a7d5-194e9db49df8.png)

Source Code on live site:
![Screenshot 2021-10-18 4 43 25 PM](https://user-images.githubusercontent.com/75644395/137811004-89cd00fe-f228-45f6-8311-737a619b2ecc.png)

Source Code uploaded to site:
![Screenshot 2021-10-18 4 45 19 PM](https://user-images.githubusercontent.com/75644395/137811157-59e1a997-db3b-4a25-b345-a3776ec91403.png)

**Comment by greenreader9** [comment]
Did a little more looking into it. If the status in the database is set to "0" or "1" ("Inactive" or "Active") nothing is shown. If the status in the database is set to "2" ("Suspended"), the message "No Domain Found".

**Comment by mahtab2003** [comment]
You need to completely update mofhy installation to work

**Comment by greenreader9** [comment]
I have already done that, the same thing happens. I will do it again though.

**Comment by greenreader9** [comment]
Nope, still not working. The account does have a domain on it though

If the status is 0 or 1 (Inactive or Active) nothing is shown.
If the status is 2 (Suspended) the "No Domain Found" text is shown

**Comment by mahtab2003** [comment]
Fixed

**Comment by greenreader9** [comment]
Still not working after fresh install

**Comment by mahtab2003** [comment]
Now it is fixed

**Comment by greenreader9** [comment]
All good now!
