### ISSUE TITLE
[FEATURE REQUEST] Add a button to check SSL records

### ISSUE THREAD

**Issue by tanguy-fgl** [mahtab2003/MOFHY-Lite#80]
please add a button to check records using the api of GoGetSSL because we can only laucnh a checking phase in the GoGetSSL client area

**Comment by greenreader9** [comment]
Just add it yourself. All it has to do is re-load the page.

**Comment by mahtab2003** [comment]
Well there is no function to reload it using Api.
Let me try to find one

**Comment by jaikt** [comment]
[there is an api function](https://documenter.getpostman.com/view/5593375/T1LHFp7m#aee8aa8b-4afd-472e-9e54-b2c65ba1861c)

**Comment by jaikt** [comment]
@greenreader9, reloading won't help. You need to tell the system to re-check the records or wait till it does that automatically withing a few days.

**Comment by greenreader9** [comment]
No, reloading will help. Please take a look at how the API works before correcting me, or if I am wrong, tell me why.

Reloading the page will get a status update from GoGetSSL API. If the client is just waiting on the page, the records may have passed, but there is no code to auto-update that page. Therefore, a reload will force the client area to get an update from the API.

**Comment by mahtab2003** [comment]
> No, reloading will help. Please take a look at how the API works before correcting me, or if I am wrong, tell me why.
> 
> Reloading the page will get a status update from GoGetSSL API. If the client is just waiting on the page, the records may have passed, but there is no code to auto-update that page. Therefore, a reload will force the client area to get an update from the API.

Let me tell you why because it is not like Lets Encrypt.
The function must be called in order to verify dns record

**Comment by mahtab2003** [comment]
Will add in up comming week
