### ISSUE TITLE
JavaScript Minifier is broken

### ISSUE THREAD

**Issue by greenreader9** [mahtab2003/MOFHY-Lite#82]
When inputting JavaScript code into the minifier, it can overflow and interfere with the page.

**To Reproduce**
1. Go to the JS minifier
2. Copy the source code for jQuery into the "input" box (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.js)
3. Click the minfiy button
4. See the overflow

**Expected behavior**
The JS stayed in the textarea for the minfied text.

**Screenshots**
![image](https://user-images.githubusercontent.com/75644395/153972707-a9332d41-ccdd-4f18-961e-7c00c9c37b47.png)

**Comment by mahtab2003** [comment]
Did you create minifier yourself?

**Comment by mahtab2003** [comment]
Use htmlentities() or htmlspecialchars() function

**Comment by greenreader9** [comment]
> Did you create minifier yourself? 

Huh. I so thought that was part of this, guess not.

**Comment by mahtab2003** [comment]
Nope
