### ISSUE TITLE
CookieHandler.php not allowed on a free hosting

### ISSUE THREAD

**Issue by OverdueWeevil2** [mahtab2003/MOFHY-Lite#83]
![](https://user-images.githubusercontent.com/67264530/154563433-62e81c37-7309-4049-95f7-3036949d2574.png)

**Comment by jaikt** [comment]
Never saw such a thing. But you can rename the file to something else, and change the new file name wherever necessary,

**Comment by mahtab2003** [comment]
I see i use token system.
Let me remove it.

**Comment by ghost** [comment]
What release are you guys using? I just finished implementing MOFHY-Lite into my hosting site, and my CookieHandler.php doesn't look like the one currently in the repository.

**Comment by mahtab2003** [comment]
Latest Dev release

**Comment by OverdueWeevil2** [comment]
![](https://user-images.githubusercontent.com/67264530/154659271-3928f95b-e8cc-43b0-9b47-62c32670765d.png)
