### ISSUE TITLE
XSS: Do not echo unencoded GET values

### ISSUE THREAD

**Issue by greenreader9** [mahtab2003/MOFHY-Lite#99]
**Describe the bug**
The application echos un-encoded GET values

**Expected behavior**
The application does not echo un-encoded GET values

**Screenshots**
Example:
![Screenshot 2022-03-18 9 58 25 AM](https://user-images.githubusercontent.com/75644395/159031190-334dc6f0-f77b-49e1-bdd1-951c07ec82d3.png)

**Additional context**
The following pages have the error:
src/admin/template/AccountSettings.php:5
src/admin/template/AccountSettings.php:5
src/template/ViewAccount.php:4
src/template/AccountSettings.php:6
src/template/ViewSSL.php:4 
src/template/cPLogin.php:5
src/template/ViewKnowledgebase.php:4
src/template/ViewKnowledgebase.php:4
src/template/ViewTicket.php:117
src/admin/template/ViewAccount.php:4

**Comment by mahtab2003** [comment]
I didn't understand what the problem is?

**Comment by greenreader9** [comment]
XSS Vulnerability 

https://stackoverflow.com/questions/28001070/prevent-from-xss-attacks-when-echoing-variables

**Comment by mahtab2003** [comment]
Ok
